# Generated by Django 3.0.8 on 2020-07-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(verbose_name='Invite code')),
                ('used', models.BooleanField(verbose_name='Used?')),
                ('used_by', models.CharField(max_length=191, verbose_name='Used by')),
            ],
        ),
    ]
