# Generated by Django 3.0.8 on 2020-07-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='code',
            field=models.UUIDField(unique=True, verbose_name='Invite code'),
        ),
    ]
