# Generated by Django 3.0.8 on 2020-07-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200725_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='used_by',
            field=models.CharField(blank=True, max_length=191, null=True, verbose_name='Used by'),
        ),
    ]
