# Generated by Django 3.0.8 on 2020-07-25 18:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20200725_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitecode',
            name='group',
            field=models.CharField(blank=True, max_length=191, null=True, verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Invite code'),
        ),
    ]
