# Generated by Django 3.0.8 on 2020-07-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20200726_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='groups',
            field=models.TextField(blank=True, null=True, verbose_name='Groups'),
        ),
    ]
